theme: jekyll-theme-hacker

title: debris-boards
google_analytics: UA-84872440-4
description: Garbage keycaps, keycaps that look like garbage, keycaps made of garbage. Debris boards.
contact: Contact me at [u/knot-a-robot](https://reddit.com/u/knot-a-robot) or [debrisboards@gmail.com](mailto:debrisboards@gmail.com?subject=[Website]%20keycaps)
